In [3]:
##Vandermonde Matrix generation
import pandas as pd
import numpy as np

In [6]:
def vander_gen(vec,n,increase=False):
    if(increase==False):
        return np.matrix([x**(n-i-1) for x in vec for i in range(n)]).reshape(vec.size,n)
    else:
        return np.matrix([x**i for x in vec for i in range(n)]).reshape(vec.size,n)

In [10]:
l=np.arange(1,5)

In [11]:
vander_gen(l,5,False)

matrix([[  1,   1,   1,   1,   1],
        [ 16,   8,   4,   2,   1],
        [ 81,  27,   9,   3,   1],
        [256,  64,  16,   4,   1]])

In [12]:
vander_gen(l,5,True)

matrix([[  1,   1,   1,   1,   1],
        [  1,   2,   4,   8,  16],
        [  1,   3,   9,  27,  81],
        [  1,   4,  16,  64, 256]])

In [14]:
def moving_avg(x,k):
    mov_avg=np.ndarray(0)
    n=np.size(x)
    w=n-k+1
    c=0
    for i in range(0,n):
        if(c<w):
            print(np.mean(x[c:c+k],dtype=float))
            mov_avg = np.mean(x[c:c+k],dtype=float)
            c+=1

In [19]:
test = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
np.array(test, dtype='int')

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [20]:
moving_avg(test,3)

5.0
4.666666666666667
5.666666666666667
6.666666666666667
9.666666666666666
28.666666666666668
49.333333333333336
72.66666666666667
84.0
93.33333333333333
116.33333333333333
